services:
  flask:
    build:
      context: .
      dockerfile: ./compose/flask/Dockerfile
    ports:
      - 8000:8000
    env_file:
      .envfiles/.backend
    environment:
      - FLASK_APP=src/runtest.py
      - LOG_DIR=/var/log/backend
    depends_on:
      - redis
    volumes:
      - ./backend/src:/backend/src
      - ./migrations/versions:/backend/migrations/versions

  redis:
    image: redis:latest
    ports:
      - 6379:6379
