services:
  backend:
    build:
      context: .
      dockerfile: ./compose/backend/Dockerfile
    container_name: mdb-flask
    command: /start
    ports:
      - 8000:8000
    env_file:
      .envfiles/.backend
    environment:
      - LOG_DIR=/data/logs/backend
      - FLASK_APP=src/run.py
    depends_on:
      - redis
    volumes:
      - ./backend/src:/backend/src
      - ./backend/migrations/versions:/backend/migrations/versions
      - ./data:/data
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"

  frontend:
    build:
      context: .
      dockerfile: ./compose/frontend/Dockerfile
    container_name: mdb-nextjs
    ports:
      - 4000:4000
    env_file:
      .envfiles/.frontend
    environment:
      - API_URL=http://host.docker.internal
      - API_PORT=8000
    depends_on:
      - backend
    volumes:
      - ./data:/data
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"


  redis:
    image: redis:latest
    container_name: mdb-redis
    command: [
      "redis-server",
      "--appendonly", "yes",
      "--appendfilename", "appendonly.aof",
      "--appendfsync", "everysec",
      "--port", "6380"]
    volumes:
      - ./data:/data
    ports:
      - "6380:6380"
    restart: unless-stopped
