[tool.pytest.ini_options]
testpaths = ["tests"]
filterwarnings = ["ignore::DeprecationWarning:marshmallow.*"]

[tool.coverage.run]
branch = true
source = ["src"]

[tool.coverage.report]
exclude_also = [
    "if TYPE_CHECKING:"
]
