"""empty message

Revision ID: 724cbd5858de
Revises: 9e8b23bb53d7
Create Date: 2025-02-01 22:13:59.354318

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '724cbd5858de'
down_revision = '9e8b23bb53d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_role',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'role_id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint('user_role_id_fkey', type_='foreignkey')
        batch_op.drop_column('role_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('user_role_id_fkey', 'role', ['role_id'], ['id'])

    op.drop_table('user_role')
    # ### end Alembic commands ###
